baseURL = 'https://arnavshukla.co/'
languageCode = 'en-us'
title = "xL's Blog"
theme = "terminal"

[params]
readMore = "read more"

[params.logo]
logoText = "xL's Blog"

[[menu.main]]
name = "counter-strike"
url = "/tags/counter-strike/"
weight = 1

[[menu.main]]
name = "esports"
url = "/tags/esports/"
weight = 2

[[menu.main]]
name = "formula 1"
url = "/tags/f1/"
weight = 3

[[menu.main]]
name = "technology"
url = "/tags/technology/"
weight = 4

[[menu.main]]
name = "media"
url = "/tags/media/"
weight = 5

[[menu.main]]
name = "random thoughts"
url = "/tags/random/"
weight = 6

[[menu.main]]
name = "resume"
url = "/resume/"
weight = 7
